### DISCUSSION TITLE
Groups customization

### DISCUSSION THREAD

**Discussion by Semigradsky** [theKashey/stylelint-semantic-groups#4] [Q&A]
My config:
```js
  rules: {
    'order/order': [
      {
        type: 'at-rule',
        name: 'include',
      },
      'custom-properties',
      'dollar-variables',
      'declarations',
      'at-rules',
      'rules',
    ],
    'order/properties-order': propertyOrdering,
    'declaration-empty-line-before': null,
  },
```
and code:
```scss
body {
  @include normal-font;

  margin: 0;
  padding: 0 1em;

  color: $bo-color-bluish-gray-4;
  font-family: $bopr-base-font-family;

  background-color: $bo-color-bluish-gray-8;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

@theKashey  Is it possible to 'extend'/'customize' `propertyOrdering` for having `@include normal-font;` in a top of `typography` group?

What I want to have:
```scss
body {
  margin: 0;
  padding: 0 1em;

  @include normal-font;
  color: $bo-color-bluish-gray-4;
  font-family: $bopr-base-font-family;

  background-color: $bo-color-bluish-gray-8;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```
